# Setting Workspace

In [ ]:
!pip install ipython-autotime
!pip install transformers

In [ ]:
%load_ext autotime

time: 73.4 µs (started: 2021-07-24 06:09:41 +00:00)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
time: 4.53 ms (started: 2021-07-24 06:09:41 +00:00)


In [ ]:
!pwd
import os
os.chdir('/content/drive/My Drive/HLT/')
!pwd

/content
/content/drive/My Drive/HLT
time: 240 ms (started: 2021-07-24 06:09:41 +00:00)


# Import Libraries

In [ ]:
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, pipeline, TFBertModel, TFAlbertModel
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,roc_auc_score,roc_curve,r2_score,recall_score,confusion_matrix,precision_recall_curve
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
import matplotlib.pyplot as plt
from tensorflow.keras.layers import InputLayer, Embedding, Concatenate, TimeDistributed, Bidirectional, GRU
from tensorflow.keras.layers import LSTM, Dense,Flatten,Conv2D,Conv1D,GlobalMaxPooling1D,GlobalMaxPool1D
from sklearn.metrics import classification_report,roc_auc_score,roc_curve,r2_score,recall_score,confusion_matrix,precision_recall_curve
import seaborn as sns
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dropout

time: 9.89 s (started: 2021-07-24 06:09:42 +00:00)


In [ ]:
pd.set_option('display.max_colwidth', -1) #show all text in col
pd.set_option('display.max_rows', None) #show all rows

time: 1.29 ms (started: 2021-07-24 06:09:51 +00:00)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


# Create albert Embeddings

In [ ]:
train_df = pd.read_csv("datasets/train.csv") 
train_df['headline']=train_df['headline'].apply(str)
train_df.head()

headline  is_sarcastic
0  bill de blasio thinks hes proved haters wrong comes prek  0           
1  baby doesnt realize white supremacist yet                 1           
2  spring sprung arctic way early                            0           
3  mayor daleys son appointed head illinois nepotist party   1           
4  poll grandsons talented                                   1

time: 63.7 ms (started: 2021-07-24 06:09:51 +00:00)


In [ ]:
test_df = pd.read_csv("datasets/test.csv") 
test_df['headline']=test_df['headline'].apply(str)
test_df.head()

headline  is_sarcastic
0  jessie james decker shares inspiring message postbaby bodies                             0           
1  frustrated russian officials struggling get policies dysfunctional trump administration  1           
2  second saturday staten island art walk                                                   0           
3  chris christie emits loud sob paul ryan asks crowd whether worse years ago               1           
4  chicago police department monitor interactions public using new bullet cams              1

time: 26.5 ms (started: 2021-07-24 06:09:52 +00:00)


In [ ]:
print("Train size:{}".format(train_df.shape))
print("Test size:{}".format(test_df.shape))

Train size:(22702, 2)
Test size:(4007, 2)
time: 4.44 ms (started: 2021-07-24 06:09:52 +00:00)


In [ ]:
train_y = train_df['is_sarcastic']
test_y = test_df['is_sarcastic']

train_x = train_df['headline']
test_x = test_df['headline']
train_x.shape,train_y.shape,test_x.shape,test_y.shape

((22702,), (22702,), (4007,), (4007,))

time: 7.21 ms (started: 2021-07-24 06:09:52 +00:00)


In [ ]:
# albert Embeddings

def transformer_embedding(name,inp,model_name):

    model = model_name.from_pretrained(name)
    tokenizer = AutoTokenizer.from_pretrained(name)
    pipe = pipeline('feature-extraction', model=model, 
                tokenizer=tokenizer)
    features = pipe(inp)
    features = np.squeeze(features)
    return features

time: 5.49 ms (started: 2021-07-24 06:09:52 +00:00)


In [ ]:
'''
Embedding trainset

'''
train_x_list = train_x.tolist()
train_y_list = train_y.to_list()

time: 9.71 ms (started: 2021-07-24 06:09:52 +00:00)


In [ ]:
len(train_x_list)

22702

time: 8.17 ms (started: 2021-07-24 06:09:52 +00:00)


In [ ]:
len(train_y_list)

22702

time: 4.11 ms (started: 2021-07-24 06:15:59 +00:00)


In [ ]:
# Embeddings trainset
embedding_features=transformer_embedding('albert-base-v1',train_x_list[20000:],TFAlbertModel)

Some layers from the model checkpoint at albert-base-v1 were not used when initializing TFAlbertModel: ['predictions']
- This IS expected if you are initializing TFAlbertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFAlbertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFAlbertModel were initialized from the model checkpoint at albert-base-v1.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFAlbertModel for predictions without further training.


time: 2min 21s (started: 2021-07-24 06:15:59 +00:00)


In [ ]:
embedding_features.shape

(2702, 25, 768)

time: 6.12 ms (started: 2021-07-24 06:18:20 +00:00)


In [ ]:
train_albert_x = embedding_features[:,0,:]

time: 1.3 ms (started: 2021-07-24 06:18:20 +00:00)


In [ ]:
train_albert_x.shape

(2702, 768)

time: 4.49 ms (started: 2021-07-24 06:18:20 +00:00)


In [ ]:
train_albert_x_df = pd.DataFrame(train_albert_x)

time: 1.85 ms (started: 2021-07-24 06:18:20 +00:00)


In [ ]:
train_albert_x_df.head()

0         1         2  ...       765       766       767
0  1.076906  0.756411  0.824502  ...  0.607596  0.590549 -0.172364
1  0.457440  0.481318  1.110510  ...  0.095153  0.350712 -0.071876
2  0.946261  0.667814  0.958797  ...  0.320204  0.613596 -0.297901
3  0.674265  0.450681  0.559820  ...  0.201958  0.875665  0.201105
4  0.875752  0.202045  1.343674  ...  0.597727  0.574817 -0.064724

[5 rows x 768 columns]

time: 123 ms (started: 2021-07-24 06:18:20 +00:00)


In [ ]:
train_albert_x_df['is_sarcastic'] = train_y_list[20000:]

time: 5.01 ms (started: 2021-07-24 06:18:20 +00:00)


In [ ]:
train_albert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0  1.076906  0.756411  0.824502  ...  0.590549 -0.172364  1           
1  0.457440  0.481318  1.110510  ...  0.350712 -0.071876  1           
2  0.946261  0.667814  0.958797  ...  0.613596 -0.297901  0           
3  0.674265  0.450681  0.559820  ...  0.875665  0.201105  1           
4  0.875752  0.202045  1.343674  ...  0.574817 -0.064724  1           

[5 rows x 769 columns]

time: 137 ms (started: 2021-07-24 06:18:20 +00:00)


In [ ]:
train_albert_x_df.to_csv('datasets/train_albert_20000_end.csv', encoding='utf-8', index=False)

time: 3.76 s (started: 2021-07-24 06:18:20 +00:00)


In [ ]:
'''
Embedding testset

'''
test_x_list = test_x.tolist()
test_y_list = test_y.to_list()

time: 1.72 ms (started: 2021-07-24 06:19:20 +00:00)


In [ ]:
len(test_x_list)

4007

time: 3.69 ms (started: 2021-07-24 06:19:21 +00:00)


In [ ]:
len(test_y_list)

4007

time: 8.11 ms (started: 2021-07-24 06:19:22 +00:00)


In [ ]:
embedding_features=transformer_embedding('albert-base-v1',test_x_list,TFAlbertModel)

Some layers from the model checkpoint at albert-base-v1 were not used when initializing TFAlbertModel: ['predictions']
- This IS expected if you are initializing TFAlbertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFAlbertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFAlbertModel were initialized from the model checkpoint at albert-base-v1.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFAlbertModel for predictions without further training.


time: 3min 8s (started: 2021-07-24 06:19:23 +00:00)


In [ ]:
embedding_features.shape

(4007, 23, 768)

time: 3.75 ms (started: 2021-07-24 06:22:31 +00:00)


In [ ]:
test_albert_x = embedding_features[:,0,:]

time: 1.04 ms (started: 2021-07-24 06:22:31 +00:00)


In [ ]:
test_albert_x.shape

(4007, 768)

time: 3.46 ms (started: 2021-07-24 06:22:31 +00:00)


In [ ]:
test_albert_x_df = pd.DataFrame(test_albert_x)

time: 1.33 ms (started: 2021-07-24 06:22:31 +00:00)


In [ ]:
test_albert_x_df.head()

0         1         2  ...       765       766       767
0  0.801973  0.603053  0.888681  ... -0.002267  0.528595 -0.280610
1  1.002656  0.740398  0.219594  ...  0.164350  0.836719 -0.214160
2  0.691385  1.107759  0.547635  ...  0.452157  1.048109 -0.476618
3  0.893270  1.039331  0.503443  ...  1.058726  0.609258 -0.264051
4  0.817568  0.982586  0.749540  ...  0.491846  0.851716  0.049653

[5 rows x 768 columns]

time: 120 ms (started: 2021-07-24 06:22:31 +00:00)


In [ ]:
test_albert_x_df['is_sarcastic'] = test_y_list

time: 4.08 ms (started: 2021-07-24 06:22:31 +00:00)


In [ ]:
test_albert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0  0.801973  0.603053  0.888681  ...  0.528595 -0.280610  0           
1  1.002656  0.740398  0.219594  ...  0.836719 -0.214160  1           
2  0.691385  1.107759  0.547635  ...  1.048109 -0.476618  0           
3  0.893270  1.039331  0.503443  ...  0.609258 -0.264051  1           
4  0.817568  0.982586  0.749540  ...  0.851716  0.049653  1           

[5 rows x 769 columns]

time: 142 ms (started: 2021-07-24 06:22:31 +00:00)


In [ ]:
test_albert_x_df.to_csv('datasets/test_albert.csv', encoding='utf-8', index=False)

time: 5.76 s (started: 2021-07-24 06:22:32 +00:00)


# Merge Trainset


In [ ]:
train_albert_1 = pd.read_csv("datasets/train_albert_0_4000.csv") 
train_albert_2 = pd.read_csv("datasets/train_albert_4000_8000.csv")
train_albert_3 = pd.read_csv("datasets/train_albert_8000_12000.csv") 
train_albert_4 = pd.read_csv("datasets/train_albert_12000_16000.csv")
train_albert_5 = pd.read_csv("datasets/train_albert_16000_20000.csv") 
train_albert_6 = pd.read_csv("datasets/train_albert_20000_end.csv") 

time: 9.3 s (started: 2021-07-24 06:23:40 +00:00)


In [ ]:
train_albert_df = train_albert_1.append([train_albert_2, train_albert_3, train_albert_4, train_albert_5, train_albert_6])

time: 49 ms (started: 2021-07-24 06:23:49 +00:00)


In [ ]:
train_albert_df.shape

(22702, 769)

time: 4.09 ms (started: 2021-07-24 06:23:49 +00:00)


In [ ]:
train_albert_df.to_csv('datasets/train_albert.csv', encoding='utf-8', index=False)

time: 33.6 s (started: 2021-07-24 06:23:49 +00:00)


# Statistical Models

In [ ]:
train_albert_df = pd.read_csv("datasets/train_albert.csv") 
train_albert_df.shape 

(22702, 769)

time: 4.76 s (started: 2021-07-24 06:24:23 +00:00)


In [ ]:
train_albert_df.head()

0         1         2  ...       766       767  is_sarcastic
0  1.023280  0.895187  0.989915  ...  0.733553 -0.344365  0           
1  0.449931  0.107994  1.609914  ...  0.237054 -0.048657  1           
2  0.601503  0.392882  1.303799  ...  0.466300  0.042190  0           
3  0.944271  1.285116  0.326767  ...  0.868670 -0.346602  1           
4  0.318234  0.158980  0.377982  ...  0.477243 -0.322496  1           

[5 rows x 769 columns]

time: 113 ms (started: 2021-07-24 06:24:28 +00:00)


In [ ]:
test_albert_df = pd.read_csv("datasets/test_albert.csv") 
test_albert_df.shape 

(4007, 769)

time: 947 ms (started: 2021-07-24 06:24:28 +00:00)


In [ ]:
train_y = train_albert_df.pop('is_sarcastic')
test_y = test_albert_df.pop('is_sarcastic')

train_x = train_albert_df
test_x = test_albert_df

train_x.shape,train_y.shape,test_x.shape,test_y.shape

((22702, 768), (22702,), (4007, 768), (4007,))

time: 9.9 ms (started: 2021-07-24 06:24:29 +00:00)


## Logistic Regression

In [ ]:
# Applying Logistic Regression on split tfidf baseline
model=LogisticRegression(max_iter=10000)
model.fit(train_x,train_y)
pred=model.predict(test_x)
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1753  495]
 [ 576 1183]]
Accuracy Score for LR with C=1.0  =0.7327177439480909
time: 23.2 s (started: 2021-07-24 06:24:29 +00:00)


## KNN

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 25, weights = 'distance')
knn.fit(train_x,train_y)
pred=knn.predict(test_x)

time: 2min 47s (started: 2021-07-24 06:24:52 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1761  487]
 [ 740 1019]]
Accuracy Score for LR with C=1.0  =0.6937858747192414
time: 8.52 ms (started: 2021-07-24 06:27:40 +00:00)


## Decision Tree

In [ ]:
dt = DecisionTreeClassifier(criterion ='entropy', max_depth= None, min_samples_leaf=1, min_samples_split=20,splitter="best")
dt.fit(train_x,train_y)
pred=dt.predict(test_x)

time: 52 s (started: 2021-07-24 06:27:40 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1414  834]
 [ 815  944]]
Accuracy Score for LR with C=1.0  =0.5884701771899177
time: 13.6 ms (started: 2021-07-24 06:28:32 +00:00)


## Random Forest

In [ ]:
rf = RandomForestClassifier(criterion='entropy',n_estimators = 100, max_depth = None, bootstrap = False)
rf.fit(train_x,train_y)
pred=rf.predict(test_x)

time: 3min 21s (started: 2021-07-24 06:28:32 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1840  408]
 [ 848  911]]
Accuracy Score for LR with C=1.0  =0.686548540054904
time: 11.1 ms (started: 2021-07-24 06:31:54 +00:00)


## Naive Bayes

In [ ]:
gnb = GaussianNB()
gnb.fit(train_x,train_y)
pred=gnb.predict(test_x)

time: 340 ms (started: 2021-07-24 06:31:54 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1381  867]
 [ 814  945]]
Accuracy Score for LR with C=1.0  =0.5804841527327177
time: 11.5 ms (started: 2021-07-24 06:31:54 +00:00)


## SVC

In [ ]:
from sklearn.svm import SVC
svc = SVC(kernel ='rbf', gamma = 0.1, C = 10, probability=True) 
svc.fit(train_x,train_y)
pred=svc.predict(test_x)

time: 3h 15min 33s (started: 2021-07-24 06:31:54 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[2042  206]
 [1143  616]]
Accuracy Score for LR with C=1.0  =0.6633391564761667
time: 21.4 ms (started: 2021-07-24 09:47:28 +00:00)
