# Setting Workspace

In [ ]:
!pip install ipython-autotime
!pip install transformers

In [ ]:
%load_ext autotime

time: 118 µs (started: 2021-08-09 08:50:59 +00:00)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
time: 3.06 ms (started: 2021-08-09 08:50:59 +00:00)


In [ ]:
!pwd
import os
os.chdir('/content/drive/My Drive/HLT/')
!pwd

/content
/content/drive/My Drive/HLT
time: 241 ms (started: 2021-08-09 08:50:59 +00:00)


# Import Libraries

In [ ]:
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, pipeline, TFBertModel
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,roc_auc_score,roc_curve,r2_score,recall_score,confusion_matrix,precision_recall_curve
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
import matplotlib.pyplot as plt
from tensorflow.keras.layers import InputLayer, Embedding, Concatenate, TimeDistributed, Bidirectional, GRU
from tensorflow.keras.layers import LSTM, Dense,Flatten,Conv2D,Conv1D,GlobalMaxPooling1D,GlobalMaxPool1D
from sklearn.metrics import classification_report,roc_auc_score,roc_curve,r2_score,recall_score,confusion_matrix,precision_recall_curve
import seaborn as sns
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dropout

time: 12.7 s (started: 2021-08-09 08:50:59 +00:00)


In [ ]:
pd.set_option('display.max_colwidth', -1) #show all text in col
pd.set_option('display.max_rows', None) #show all rows

time: 3.47 ms (started: 2021-08-09 08:51:12 +00:00)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


# Create Bert Embeddings

In [ ]:
train_df = pd.read_csv("datasets/train.csv") 
train_df['headline']=train_df['headline'].apply(str)
train_df.head()

headline  is_sarcastic
0  bill de blasio thinks proved haters wrong comes pre k   0           
1  baby realize white supremacist yet                      1           
2  spring sprung arctic way early                          0           
3  mayor daley son appointed head illinois nepotist party  1           
4  poll grandsons talented                                 1

time: 994 ms (started: 2021-08-09 07:47:43 +00:00)


In [ ]:
test_df = pd.read_csv("datasets/test.csv") 
test_df['headline']=test_df['headline'].apply(str)
test_df.head()

headline  is_sarcastic
0  jessie james decker shares inspiring message post baby bodies                            0           
1  frustrated russian officials struggling get policies dysfunctional trump administration  1           
2  second saturday staten island art walk                                                   0           
3  chris christie emits loud sob paul ryan asks crowd whether worse years ago               1           
4  chicago police department monitor interactions public using new bullet cams              1

time: 412 ms (started: 2021-08-09 07:47:44 +00:00)


In [ ]:
print("Train size:{}".format(train_df.shape))
print("Test size:{}".format(test_df.shape))

Train size:(22702, 2)
Test size:(4007, 2)
time: 3.18 ms (started: 2021-08-09 07:47:45 +00:00)


In [ ]:
train_y = train_df['is_sarcastic']
test_y = test_df['is_sarcastic']

train_x = train_df['headline']
test_x = test_df['headline']
train_x.shape,train_y.shape,test_x.shape,test_y.shape

((22702,), (22702,), (4007,), (4007,))

time: 6.08 ms (started: 2021-08-09 07:47:45 +00:00)


In [ ]:
# BERT Embeddings

def transformer_embedding(name,inp,model_name):

    model = model_name.from_pretrained(name)
    tokenizer = AutoTokenizer.from_pretrained(name)
    pipe = pipeline('feature-extraction', model=model, 
                tokenizer=tokenizer)
    features = pipe(inp)
    features = np.squeeze(features)
    return features

time: 5.41 ms (started: 2021-08-09 07:47:46 +00:00)


In [ ]:
'''
Embedding trainset

'''
train_x_list = train_x.tolist()
train_y_list = train_y.to_list()

time: 2.7 ms (started: 2021-08-09 07:48:37 +00:00)


In [ ]:
len(train_x_list)

22702

time: 4.07 ms (started: 2021-08-09 07:48:38 +00:00)


In [ ]:
len(train_y_list)

22702

time: 11.5 ms (started: 2021-08-09 07:48:39 +00:00)


## Train 1

In [ ]:
# Embeddings trainset
embedding_features=transformer_embedding('bert-base-uncased',train_x_list[0:4000],TFBertModel)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.



time: 5min 36s (started: 2021-08-09 07:51:12 +00:00)


In [ ]:
embedding_features.shape

(4000, 37, 768)

time: 7.08 ms (started: 2021-08-09 07:56:49 +00:00)


In [ ]:
train_bert_x = embedding_features[:,0,:]

time: 1.76 ms (started: 2021-08-09 07:56:49 +00:00)


In [ ]:
train_bert_x.shape

(4000, 768)

time: 3.76 ms (started: 2021-08-09 07:56:49 +00:00)


In [ ]:
train_bert_x_df = pd.DataFrame(train_bert_x)

time: 4.23 ms (started: 2021-08-09 07:56:49 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       765       766       767
0 -0.190443  0.249115  0.230637  ... -0.199147  0.484466  0.361765
1 -0.492397 -0.027411 -0.332466  ... -0.330648  0.540078  0.175039
2 -0.142799 -0.049289  0.228374  ... -0.315215  0.064099  0.204661
3 -0.868000 -0.101078 -0.575666  ... -0.350663  0.440300  0.144549
4 -0.766649 -0.008375 -0.152243  ... -0.312135  0.372962  0.300498

[5 rows x 768 columns]

time: 149 ms (started: 2021-08-09 07:56:49 +00:00)


In [ ]:
train_bert_x_df['is_sarcastic'] = train_y_list[0:4000]

time: 5.73 ms (started: 2021-08-09 07:56:49 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0 -0.190443  0.249115  0.230637  ...  0.484466  0.361765  0           
1 -0.492397 -0.027411 -0.332466  ...  0.540078  0.175039  1           
2 -0.142799 -0.049289  0.228374  ...  0.064099  0.204661  0           
3 -0.868000 -0.101078 -0.575666  ...  0.440300  0.144549  1           
4 -0.766649 -0.008375 -0.152243  ...  0.372962  0.300498  1           

[5 rows x 769 columns]

time: 140 ms (started: 2021-08-09 07:56:49 +00:00)


In [ ]:
train_bert_x_df.to_csv('datasets/BERT/train_bert_0_4000.csv', encoding='utf-8', index=False)

time: 5.85 s (started: 2021-08-09 07:56:49 +00:00)


## Train 2

In [ ]:
# Embeddings trainset
embedding_features=transformer_embedding('bert-base-uncased',train_x_list[4000:8000],TFBertModel)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


time: 3min 32s (started: 2021-08-09 08:05:46 +00:00)


In [ ]:
embedding_features.shape

(4000, 24, 768)

time: 5.29 ms (started: 2021-08-09 08:09:19 +00:00)


In [ ]:
train_bert_x = embedding_features[:,0,:]

time: 732 µs (started: 2021-08-09 08:09:19 +00:00)


In [ ]:
train_bert_x.shape

(4000, 768)

time: 5.48 ms (started: 2021-08-09 08:09:19 +00:00)


In [ ]:
train_bert_x_df = pd.DataFrame(train_bert_x)

time: 2.69 ms (started: 2021-08-09 08:09:19 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       765       766       767
0 -0.487389  0.095127 -0.388939  ... -0.203853  0.046877  0.527030
1 -0.243699  0.218615  0.130719  ... -0.486827  0.259728 -0.025763
2  0.533739  0.197596 -0.057717  ... -0.445710  0.278400 -0.038013
3 -0.738714 -0.258002 -0.361993  ... -0.061490  0.106860  0.288059
4 -0.699753 -0.206459 -0.088463  ... -0.256726  0.117932  0.073231

[5 rows x 768 columns]

time: 181 ms (started: 2021-08-09 08:09:19 +00:00)


In [ ]:
train_bert_x_df['is_sarcastic'] = train_y_list[4000:8000]

time: 6.7 ms (started: 2021-08-09 08:09:19 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0 -0.487389  0.095127 -0.388939  ...  0.046877  0.527030  1           
1 -0.243699  0.218615  0.130719  ...  0.259728 -0.025763  1           
2  0.533739  0.197596 -0.057717  ...  0.278400 -0.038013  1           
3 -0.738714 -0.258002 -0.361993  ...  0.106860  0.288059  0           
4 -0.699753 -0.206459 -0.088463  ...  0.117932  0.073231  0           

[5 rows x 769 columns]

time: 157 ms (started: 2021-08-09 08:09:19 +00:00)


In [ ]:
train_bert_x_df.to_csv('datasets/BERT/train_bert_4000_8000.csv', encoding='utf-8', index=False)

time: 5.62 s (started: 2021-08-09 08:09:19 +00:00)


## Train 3

In [ ]:
# Embeddings trainset
embedding_features=transformer_embedding('bert-base-uncased',train_x_list[8000:12000],TFBertModel)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


time: 4min 41s (started: 2021-08-09 08:09:25 +00:00)


In [ ]:
embedding_features.shape

(4000, 32, 768)

time: 4.3 ms (started: 2021-08-09 08:14:07 +00:00)


In [ ]:
train_bert_x = embedding_features[:,0,:]

time: 1.45 ms (started: 2021-08-09 08:14:07 +00:00)


In [ ]:
train_bert_x.shape

(4000, 768)

time: 4.14 ms (started: 2021-08-09 08:14:07 +00:00)


In [ ]:
train_bert_x_df = pd.DataFrame(train_bert_x)

time: 1.94 ms (started: 2021-08-09 08:14:07 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       765       766       767
0 -0.650271 -0.231898 -0.445162  ... -0.186468  0.100707  0.258762
1 -0.419367  0.051144  0.133037  ... -0.322405  0.111364 -0.108244
2 -0.027137  0.103812  0.199558  ... -0.271953  0.087871  0.194466
3 -0.461840 -0.149302 -0.083925  ... -0.169794  0.381066  0.113475
4 -0.178150  0.525380 -0.003894  ... -0.441533  0.190291  0.582038

[5 rows x 768 columns]

time: 117 ms (started: 2021-08-09 08:14:07 +00:00)


In [ ]:
train_bert_x_df['is_sarcastic'] = train_y_list[8000:12000]

time: 5.55 ms (started: 2021-08-09 08:14:07 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0 -0.650271 -0.231898 -0.445162  ...  0.100707  0.258762  0           
1 -0.419367  0.051144  0.133037  ...  0.111364 -0.108244  1           
2 -0.027137  0.103812  0.199558  ...  0.087871  0.194466  0           
3 -0.461840 -0.149302 -0.083925  ...  0.381066  0.113475  1           
4 -0.178150  0.525380 -0.003894  ...  0.190291  0.582038  0           

[5 rows x 769 columns]

time: 126 ms (started: 2021-08-09 08:14:07 +00:00)


In [ ]:
train_bert_x_df.to_csv('datasets/BERT/train_bert_8000_12000.csv', encoding='utf-8', index=False)

time: 5.7 s (started: 2021-08-09 08:14:07 +00:00)


## Train 4

In [ ]:
# Embeddings trainset
embedding_features=transformer_embedding('bert-base-uncased',train_x_list[12000:16000],TFBertModel)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


time: 5min 48s (started: 2021-08-09 08:14:13 +00:00)


In [ ]:
embedding_features.shape

(4000, 35, 768)

time: 65.5 ms (started: 2021-08-09 08:20:01 +00:00)


In [ ]:
train_bert_x = embedding_features[:,0,:]

time: 1.41 ms (started: 2021-08-09 08:20:01 +00:00)


In [ ]:
train_bert_x.shape

(4000, 768)

time: 8.59 ms (started: 2021-08-09 08:20:01 +00:00)


In [ ]:
train_bert_x_df = pd.DataFrame(train_bert_x)

time: 2.33 ms (started: 2021-08-09 08:20:02 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       765       766       767
0 -0.244856  0.004846  0.159973  ... -0.438728  0.060710  0.241150
1 -0.656429  0.833665 -0.566433  ... -0.327188  0.514018  0.157723
2 -0.245419  0.159389 -0.227434  ... -0.285171  0.192953  0.618247
3 -0.538403 -0.262061  0.224823  ... -0.984094  0.332428  0.351421
4 -0.253055  0.145976 -0.099600  ... -0.143933  0.208420  0.700638

[5 rows x 768 columns]

time: 124 ms (started: 2021-08-09 08:20:02 +00:00)


In [ ]:
train_bert_x_df['is_sarcastic'] = train_y_list[12000:16000]

time: 5.87 ms (started: 2021-08-09 08:20:02 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0 -0.244856  0.004846  0.159973  ...  0.060710  0.241150  1           
1 -0.656429  0.833665 -0.566433  ...  0.514018  0.157723  0           
2 -0.245419  0.159389 -0.227434  ...  0.192953  0.618247  0           
3 -0.538403 -0.262061  0.224823  ...  0.332428  0.351421  0           
4 -0.253055  0.145976 -0.099600  ...  0.208420  0.700638  0           

[5 rows x 769 columns]

time: 138 ms (started: 2021-08-09 08:20:02 +00:00)


In [ ]:
train_bert_x_df.to_csv('datasets/BERT/train_bert_12000_16000.csv', encoding='utf-8', index=False)

time: 5.6 s (started: 2021-08-09 08:20:02 +00:00)


## Train 5

In [ ]:
# Embeddings trainset
embedding_features=transformer_embedding('bert-base-uncased',train_x_list[16000:20000],TFBertModel)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


time: 4min (started: 2021-08-09 08:20:09 +00:00)


In [ ]:
embedding_features.shape

(4000, 26, 768)

time: 4.03 ms (started: 2021-08-09 08:24:09 +00:00)


In [ ]:
train_bert_x = embedding_features[:,0,:]

time: 1.24 ms (started: 2021-08-09 08:24:09 +00:00)


In [ ]:
train_bert_x.shape

(4000, 768)

time: 5.36 ms (started: 2021-08-09 08:24:09 +00:00)


In [ ]:
train_bert_x_df = pd.DataFrame(train_bert_x)

time: 1.08 ms (started: 2021-08-09 08:24:09 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       765       766       767
0 -0.460084  0.163162 -0.181882  ... -0.103452  0.065068  0.025327
1  0.234874  0.227259 -0.148727  ... -0.638600  0.205398  0.347954
2 -0.215381  0.512613 -0.382492  ...  0.116038  0.305904  0.003967
3 -0.377358  0.247247 -0.130909  ... -0.398110  0.036920  0.349323
4 -0.153325  0.097113  0.106691  ... -0.489169  0.076727 -0.040076

[5 rows x 768 columns]

time: 258 ms (started: 2021-08-09 08:24:09 +00:00)


In [ ]:
train_bert_x_df['is_sarcastic'] = train_y_list[16000:20000]

time: 4.16 ms (started: 2021-08-09 08:24:10 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0 -0.460084  0.163162 -0.181882  ...  0.065068  0.025327  1           
1  0.234874  0.227259 -0.148727  ...  0.205398  0.347954  0           
2 -0.215381  0.512613 -0.382492  ...  0.305904  0.003967  0           
3 -0.377358  0.247247 -0.130909  ...  0.036920  0.349323  0           
4 -0.153325  0.097113  0.106691  ...  0.076727 -0.040076  0           

[5 rows x 769 columns]

time: 145 ms (started: 2021-08-09 08:24:10 +00:00)


In [ ]:
train_bert_x_df.to_csv('datasets/BERT/train_bert_16000_20000.csv', encoding='utf-8', index=False)

time: 5.57 s (started: 2021-08-09 08:24:10 +00:00)


## Train 6

In [ ]:
# Embeddings trainset
embedding_features=transformer_embedding('bert-base-uncased',train_x_list[20000:],TFBertModel)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


time: 2min 33s (started: 2021-08-09 08:24:17 +00:00)


In [ ]:
embedding_features.shape

(2702, 24, 768)

time: 13.7 ms (started: 2021-08-09 08:26:50 +00:00)


In [ ]:
train_bert_x = embedding_features[:,0,:]

time: 1.14 ms (started: 2021-08-09 08:26:50 +00:00)


In [ ]:
train_bert_x.shape

(2702, 768)

time: 15 ms (started: 2021-08-09 08:26:50 +00:00)


In [ ]:
train_bert_x_df = pd.DataFrame(train_bert_x)

time: 2.2 ms (started: 2021-08-09 08:26:50 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       765       766       767
0 -0.374636  0.189897  0.226349  ... -0.366739  0.412987  0.115466
1 -0.477136  0.287175 -0.361060  ... -0.279687  0.624516  0.342371
2 -0.464161 -0.272234  0.179644  ... -0.625021  0.078467  0.032596
3 -0.072345  0.034758  0.298465  ... -0.449727  0.146619  0.548404
4 -0.422635  0.269720 -0.039875  ... -0.240568  0.316730  0.606972

[5 rows x 768 columns]

time: 145 ms (started: 2021-08-09 08:26:50 +00:00)


In [ ]:
train_bert_x_df['is_sarcastic'] = train_y_list[20000:]

time: 4.65 ms (started: 2021-08-09 08:26:51 +00:00)


In [ ]:
train_bert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0 -0.374636  0.189897  0.226349  ...  0.412987  0.115466  1           
1 -0.477136  0.287175 -0.361060  ...  0.624516  0.342371  1           
2 -0.464161 -0.272234  0.179644  ...  0.078467  0.032596  0           
3 -0.072345  0.034758  0.298465  ...  0.146619  0.548404  1           
4 -0.422635  0.269720 -0.039875  ...  0.316730  0.606972  1           

[5 rows x 769 columns]

time: 140 ms (started: 2021-08-09 08:26:51 +00:00)


In [ ]:
train_bert_x_df.to_csv('datasets/BERT/train_bert_20000_end.csv', encoding='utf-8', index=False)

time: 3.83 s (started: 2021-08-09 08:26:51 +00:00)


## Test 1

In [ ]:
'''
Embedding testset

'''
test_x_list = test_x.tolist()
test_y_list = test_y.to_list()

time: 3.16 ms (started: 2021-08-09 08:26:55 +00:00)


In [ ]:
len(test_x_list)

4007

time: 4.95 ms (started: 2021-08-09 08:26:55 +00:00)


In [ ]:
len(test_y_list)

4007

time: 5.81 ms (started: 2021-08-09 08:26:55 +00:00)


In [ ]:
# Embeddings trainset
embedding_features=transformer_embedding('bert-base-uncased',test_x_list,TFBertModel)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


time: 3min 34s (started: 2021-08-09 08:26:55 +00:00)


In [ ]:
embedding_features.shape

(4007, 23, 768)

time: 13.3 ms (started: 2021-08-09 08:30:29 +00:00)


In [ ]:
test_bert_x = embedding_features[:,0,:]

time: 1.21 ms (started: 2021-08-09 08:30:29 +00:00)


In [ ]:
test_bert_x.shape

(4007, 768)

time: 11.3 ms (started: 2021-08-09 08:30:29 +00:00)


In [ ]:
test_bert_x_df = pd.DataFrame(test_bert_x)

time: 4.02 ms (started: 2021-08-09 08:30:29 +00:00)


In [ ]:
test_bert_x_df.head()

0         1         2  ...       765       766       767
0  0.107940  0.127326  0.268592  ... -0.336589  0.180523  0.076551
1 -0.282037 -0.019341 -0.257521  ... -0.503066  0.430263  0.223601
2 -0.735360 -0.271005 -0.020413  ...  0.017858  0.215072  0.349393
3 -0.445481  0.160300  0.338873  ... -0.477929  0.465422  0.307502
4 -0.411752  0.104325 -0.011243  ... -0.759657  0.091118  0.036069

[5 rows x 768 columns]

time: 144 ms (started: 2021-08-09 08:30:29 +00:00)


In [ ]:
test_bert_x_df['is_sarcastic'] = test_y_list

time: 9.01 ms (started: 2021-08-09 08:30:29 +00:00)


In [ ]:
test_bert_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0  0.107940  0.127326  0.268592  ...  0.180523  0.076551  0           
1 -0.282037 -0.019341 -0.257521  ...  0.430263  0.223601  1           
2 -0.735360 -0.271005 -0.020413  ...  0.215072  0.349393  0           
3 -0.445481  0.160300  0.338873  ...  0.465422  0.307502  1           
4 -0.411752  0.104325 -0.011243  ...  0.091118  0.036069  1           

[5 rows x 769 columns]

time: 142 ms (started: 2021-08-09 08:30:29 +00:00)


In [ ]:
test_bert_x_df.to_csv('datasets/BERT/test_bert.csv', encoding='utf-8', index=False)

time: 5.64 s (started: 2021-08-09 08:30:29 +00:00)


# Merge Trainset


In [ ]:
train_bert_1 = pd.read_csv("datasets/BERT/train_bert_0_4000.csv") 
train_bert_2 = pd.read_csv("datasets/BERT/train_bert_4000_8000.csv")
train_bert_3 = pd.read_csv("datasets/BERT/train_bert_8000_12000.csv") 
train_bert_4 = pd.read_csv("datasets/BERT/train_bert_12000_16000.csv")
train_bert_5 = pd.read_csv("datasets/BERT/train_bert_16000_20000.csv")
train_bert_6 = pd.read_csv("datasets/BERT/train_bert_20000_end.csv")    

time: 11.4 s (started: 2021-08-09 08:30:36 +00:00)


In [ ]:
train_bert_df = train_bert_1.append([train_bert_2, train_bert_3, train_bert_4, train_bert_5, train_bert_6])

time: 56.5 ms (started: 2021-08-09 08:30:48 +00:00)


In [ ]:
train_bert_df.shape

(22702, 769)

time: 6.51 ms (started: 2021-08-09 08:30:48 +00:00)


In [ ]:
train_bert_df.to_csv('datasets/BERT/train_bert.csv', encoding='utf-8', index=False)

time: 45.2 s (started: 2021-08-09 08:30:48 +00:00)


# Statistical Models

In [ ]:
train_bert_df = pd.read_csv("datasets/BERT/train_bert.csv") 
train_bert_df.shape 

(22702, 769)

time: 5.58 s (started: 2021-08-09 08:51:12 +00:00)


In [ ]:
train_bert_df.head()

0         1         2  ...       766       767  is_sarcastic
0 -0.190443  0.249115  0.230637  ...  0.484466  0.361765  0           
1 -0.492397 -0.027411 -0.332466  ...  0.540078  0.175039  1           
2 -0.142799 -0.049289  0.228374  ...  0.064099  0.204661  0           
3 -0.868000 -0.101078 -0.575666  ...  0.440300  0.144549  1           
4 -0.766649 -0.008375 -0.152243  ...  0.372962  0.300498  1           

[5 rows x 769 columns]

time: 141 ms (started: 2021-08-09 08:51:18 +00:00)


In [ ]:
test_bert_df = pd.read_csv("datasets/BERT/test_bert.csv") 
test_bert_df.shape 

(4007, 769)

time: 1.04 s (started: 2021-08-09 08:51:18 +00:00)


In [ ]:
train_y = train_bert_df.pop('is_sarcastic')
test_y = test_bert_df.pop('is_sarcastic')

train_x = train_bert_df
test_x = test_bert_df

train_x.shape,train_y.shape,test_x.shape,test_y.shape

((22702, 768), (22702,), (4007, 768), (4007,))

time: 14.3 ms (started: 2021-08-09 08:51:19 +00:00)


## SVC

In [ ]:
from sklearn.svm import SVC
svc = SVC(kernel ='rbf', gamma = 0.1, C = 10, probability=True) #2h 56min
svc.fit(train_x,train_y)
pred=svc.predict(test_x)

time: 2h 58min 5s (started: 2021-08-09 08:51:19 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1990  258]
 [ 664 1095]]
Accuracy Score for LR with C=1.0  =0.7699026703269278
time: 15.6 ms (started: 2021-08-09 11:49:25 +00:00)


## Logistic Regression

In [ ]:
# Applying Logistic Regression on split tfidf baseline
model=LogisticRegression(max_iter=10000)
model.fit(train_x,train_y)
pred=model.predict(test_x)
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1860  388]
 [ 461 1298]]
Accuracy Score for LR with C=1.0  =0.7881207886199152
time: 25.4 s (started: 2021-08-09 11:49:25 +00:00)


## KNN

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 25, weights = 'distance')
knn.fit(train_x,train_y)
pred=knn.predict(test_x)

time: 2min 48s (started: 2021-08-09 11:49:50 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1805  443]
 [ 541 1218]]
Accuracy Score for LR with C=1.0  =0.7544297479411031
time: 10.5 ms (started: 2021-08-09 11:52:39 +00:00)


## Decision Tree

In [ ]:
dt = DecisionTreeClassifier(criterion ='entropy', max_depth= None, min_samples_leaf=1, min_samples_split=20,splitter="best")
dt.fit(train_x,train_y)
pred=dt.predict(test_x)

time: 48.9 s (started: 2021-08-09 11:52:39 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1534  714]
 [ 771  988]]
Accuracy Score for LR with C=1.0  =0.6293985525330671
time: 9.04 ms (started: 2021-08-09 11:53:28 +00:00)


## Random Forest

In [ ]:
rf = RandomForestClassifier(criterion='entropy',n_estimators = 100, max_depth = None, bootstrap = False)
rf.fit(train_x,train_y)
pred=rf.predict(test_x)

time: 3min 8s (started: 2021-08-09 11:53:28 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1925  323]
 [ 720 1039]]
Accuracy Score for LR with C=1.0  =0.7397055153481408
time: 10.5 ms (started: 2021-08-09 11:56:37 +00:00)


## Naive Bayes

In [ ]:
gnb = GaussianNB()
gnb.fit(train_x,train_y)
pred=gnb.predict(test_x)

time: 537 ms (started: 2021-08-09 11:56:37 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1581  667]
 [ 585 1174]]
Accuracy Score for LR with C=1.0  =0.6875467931120539
time: 15.4 ms (started: 2021-08-09 11:56:37 +00:00)
