# Setting Workspace

In [ ]:
!pip install ipython-autotime
!pip install transformers

     |████████████████████████████████| 2.6 MB 8.5 MB/s 
     |████████████████████████████████| 3.3 MB 42.1 MB/s 
     |████████████████████████████████| 636 kB 21.6 MB/s 
     |████████████████████████████████| 895 kB 40.1 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
%load_ext autotime

time: 134 µs (started: 2021-07-24 05:18:42 +00:00)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
time: 16.2 s (started: 2021-07-24 05:18:42 +00:00)


In [ ]:
!pwd
import os
os.chdir('/content/drive/My Drive/HLT/')
!pwd

/content
/content/drive/My Drive/HLT
time: 262 ms (started: 2021-07-24 05:18:59 +00:00)


# Import Libraries

In [ ]:
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, pipeline, TFBertModel, TFGPT2Model, TFOpenAIGPTModel
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,roc_auc_score,roc_curve,r2_score,recall_score,confusion_matrix,precision_recall_curve
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
import matplotlib.pyplot as plt
from tensorflow.keras.layers import InputLayer, Embedding, Concatenate, TimeDistributed, Bidirectional, GRU
from tensorflow.keras.layers import LSTM, Dense,Flatten,Conv2D,Conv1D,GlobalMaxPooling1D,GlobalMaxPool1D
from sklearn.metrics import classification_report,roc_auc_score,roc_curve,r2_score,recall_score,confusion_matrix,precision_recall_curve
import seaborn as sns
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dropout

time: 8.2 s (started: 2021-07-24 05:18:59 +00:00)


In [ ]:
pd.set_option('display.max_colwidth', -1) #show all text in col
pd.set_option('display.max_rows', None) #show all rows

time: 3.55 ms (started: 2021-07-24 05:19:07 +00:00)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


# Create GPT-2

In [ ]:
train_df = pd.read_csv("datasets/train.csv") 
train_df['headline']=train_df['headline'].apply(str)
train_df.head()

headline  is_sarcastic
0  bill de blasio thinks hes proved haters wrong comes prek  0           
1  baby doesnt realize white supremacist yet                 1           
2  spring sprung arctic way early                            0           
3  mayor daleys son appointed head illinois nepotist party   1           
4  poll grandsons talented                                   1

time: 54.3 ms (started: 2021-07-23 20:09:47 +00:00)


In [ ]:
test_df = pd.read_csv("datasets/test.csv") 
test_df['headline']=test_df['headline'].apply(str)
test_df.head()

headline  is_sarcastic
0  jessie james decker shares inspiring message postbaby bodies                             0           
1  frustrated russian officials struggling get policies dysfunctional trump administration  1           
2  second saturday staten island art walk                                                   0           
3  chris christie emits loud sob paul ryan asks crowd whether worse years ago               1           
4  chicago police department monitor interactions public using new bullet cams              1

time: 24.9 ms (started: 2021-07-23 20:09:47 +00:00)


In [ ]:
print("Train size:{}".format(train_df.shape))
print("Test size:{}".format(test_df.shape))

Train size:(22702, 2)
Test size:(4007, 2)
time: 2.41 ms (started: 2021-07-23 20:09:47 +00:00)


In [ ]:
train_y = train_df['is_sarcastic']
test_y = test_df['is_sarcastic']

train_x = train_df['headline']
test_x = test_df['headline']
train_x.shape,train_y.shape,test_x.shape,test_y.shape

((22702,), (22702,), (4007,), (4007,))

time: 6.12 ms (started: 2021-07-23 20:09:47 +00:00)


In [ ]:
def transformer_gpt_embedding(name,inp,model_name):

    model = model_name.from_pretrained(name)
    tokenizer = AutoTokenizer.from_pretrained(name)
    tokenizer.pad_token = "[PAD]"
    pipe = pipeline('feature-extraction', model=model, 
                tokenizer=tokenizer)
    features = pipe(inp)
    features = np.squeeze(features)
    return features

time: 3.99 ms (started: 2021-07-23 20:09:48 +00:00)


In [ ]:
'''
Embedding trainset

'''
train_x_list = train_x.tolist()
train_y_list = train_y.to_list()

time: 2.19 ms (started: 2021-07-23 20:09:48 +00:00)


In [ ]:
len(train_x_list)

22702

time: 3.13 ms (started: 2021-07-23 20:09:48 +00:00)


In [ ]:
len(train_y_list)

22702

time: 2.98 ms (started: 2021-07-23 20:09:48 +00:00)


In [ ]:
embedding_features=transformer_gpt_embedding('openai-gpt',train_x_list[16000:18000],TFGPT2Model)

You are using a model of type openai-gpt to instantiate a model of type gpt2. This is not supported for all configurations of models and can yield errors.
Some layers from the model checkpoint at openai-gpt were not used when initializing TFGPT2Model: ['transformer/positions_embed/embeddings:0', 'transformer/tokens_embed/weight:0']
- This IS expected if you are initializing TFGPT2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFGPT2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFGPT2Model were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['transformer/wpe/embeddings:0', 'transformer/ln_f/gamma:0', 'transformer/wte/weight:0', 'tran

time: 1min 54s (started: 2021-07-23 20:09:48 +00:00)


In [ ]:
embedding_features.shape

(2000, 22, 768)

time: 39.1 ms (started: 2021-07-23 20:11:42 +00:00)


In [ ]:
train_gpt_2_x = embedding_features[:,0,:]

time: 815 µs (started: 2021-07-23 20:11:42 +00:00)


In [ ]:
train_gpt_2_x.shape

(2000, 768)

time: 4.19 ms (started: 2021-07-23 20:11:42 +00:00)


In [ ]:
train_gpt_2_x_df = pd.DataFrame(train_gpt_2_x)

time: 1.24 ms (started: 2021-07-23 20:11:42 +00:00)


In [ ]:
train_gpt_2_x_df.head()

0         1         2  ...       765       766       767
0 -0.002061 -0.002264  0.180387  ... -0.194209 -0.002806  0.088657
1  0.035570 -0.078747  0.166971  ... -0.320861  0.069199  0.189032
2  0.063276  0.049074  0.089819  ... -0.050599 -0.123835  0.135782
3 -0.029102  0.013758  0.198493  ... -0.101002 -0.244339  0.024031
4  0.091385  0.042672  0.114439  ... -0.055694 -0.025824  0.180368

[5 rows x 768 columns]

time: 156 ms (started: 2021-07-23 20:11:42 +00:00)


In [ ]:
train_gpt_2_x_df['is_sarcastic'] = train_y_list[16000:18000]

time: 2.77 ms (started: 2021-07-23 20:11:43 +00:00)


In [ ]:
train_gpt_2_x_df.head()

0         1         2  ...       766       767  is_sarcastic
0 -0.002061 -0.002264  0.180387  ... -0.002806  0.088657  1           
1  0.035570 -0.078747  0.166971  ...  0.069199  0.189032  0           
2  0.063276  0.049074  0.089819  ... -0.123835  0.135782  0           
3 -0.029102  0.013758  0.198493  ... -0.244339  0.024031  0           
4  0.091385  0.042672  0.114439  ... -0.025824  0.180368  0           

[5 rows x 769 columns]

time: 108 ms (started: 2021-07-23 20:11:43 +00:00)


In [ ]:
train_gpt_2_x_df.to_csv('datasets/train_gpt_2_16000_18000.csv', encoding='utf-8', index=False)

time: 2.25 s (started: 2021-07-23 20:11:43 +00:00)


In [ ]:
'''
Embedding testset

'''
test_x_list = test_x.tolist()
test_y_list = test_y.to_list()

time: 1.74 ms (started: 2021-07-23 19:52:47 +00:00)


In [ ]:
len(test_x_list)

4007

time: 3.47 ms (started: 2021-07-23 19:52:49 +00:00)


In [ ]:
len(test_y_list)

4007

time: 3.07 ms (started: 2021-07-23 20:07:17 +00:00)


In [ ]:
embedding_features=transformer_gpt_embedding('openai-gpt', test_x_list[2000:],TFGPT2Model)

In [ ]:
embedding_features.shape

In [ ]:
test_gpt_2_x = embedding_features[:,0,:]

In [ ]:
test_gpt_2_x.shape

In [ ]:
test_gpt_2_x_df = pd.DataFrame(test_gpt_2_x)

In [ ]:
test_gpt_2_x_df.head()

In [ ]:
test_gpt_2_x_df['is_sarcastic'] = test_y_list[2000:]

In [ ]:
test_gpt_2_x_df.head()

In [ ]:
test_gpt_2_x_df.to_csv('datasets/test_gpt_2_2000_end.csv', encoding='utf-8', index=False)

time: 2.24 s (started: 2021-07-23 19:59:12 +00:00)


# Merge Trainset


## Train

In [ ]:
train_gpt_2_1 = pd.read_csv("datasets/train_gpt_2_0_2000.csv") 
train_gpt_2_2 = pd.read_csv("datasets/train_gpt_2_2000_4000.csv") 
train_gpt_2_3 = pd.read_csv("datasets/train_gpt_2_4000_6000.csv") 
train_gpt_2_4 = pd.read_csv("datasets/train_gpt_2_6000_8000.csv") 
train_gpt_2_5 = pd.read_csv("datasets/train_gpt_2_8000_10000.csv") 
train_gpt_2_6 = pd.read_csv("datasets/train_gpt_2_10000_12000.csv") 
train_gpt_2_7 = pd.read_csv("datasets/train_gpt_2_12000_14000.csv") 
train_gpt_2_8 = pd.read_csv("datasets/train_gpt_2_14000_16000.csv")
train_gpt_2_9 = pd.read_csv("datasets/train_gpt_2_16000_18000.csv")
train_gpt_2_10 = pd.read_csv("datasets/train_gpt_2_18000_20000.csv") 
train_gpt_2_11 = pd.read_csv("datasets/train_gpt_2_20000_end.csv") 

time: 4.1 s (started: 2021-07-23 20:12:03 +00:00)


In [ ]:
train_gpt_2_df = train_gpt_2_1.append([train_gpt_2_2, train_gpt_2_3, train_gpt_2_4, train_gpt_2_5, train_gpt_2_6, train_gpt_2_7, train_gpt_2_8, train_gpt_2_9, train_gpt_2_10, train_gpt_2_11])

time: 35.3 ms (started: 2021-07-23 20:12:08 +00:00)


In [ ]:
train_gpt_2_df.shape

(22702, 769)

time: 3.49 ms (started: 2021-07-23 20:12:09 +00:00)


In [ ]:
train_gpt_2_df.to_csv('datasets/train_gpt_2.csv', encoding='utf-8', index=False)

time: 26.9 s (started: 2021-07-23 20:12:13 +00:00)


## Test

In [ ]:
test_gpt_2_1 = pd.read_csv("datasets/test_gpt_2_0_2000.csv") 
test_gpt_2_2 = pd.read_csv("datasets/test_gpt_2_2000_end.csv") 

time: 772 ms (started: 2021-07-23 20:14:25 +00:00)


In [ ]:
test_gpt_2_df = test_gpt_2_1.append([test_gpt_2_2])

time: 9.87 ms (started: 2021-07-23 20:14:29 +00:00)


In [ ]:
test_gpt_2_df.shape

(4007, 769)

time: 5.81 ms (started: 2021-07-23 20:14:35 +00:00)


In [ ]:
test_gpt_2_df.to_csv('datasets/test_gpt_2.csv', encoding='utf-8', index=False)

time: 4.89 s (started: 2021-07-23 20:14:46 +00:00)


# Statistical Models

In [ ]:
train_gpt_2_df = pd.read_csv("datasets/train_gpt_2.csv") 
train_gpt_2_df.shape 

(22702, 769)

time: 8.4 s (started: 2021-07-24 05:19:07 +00:00)


In [ ]:
train_gpt_2_df.head()

0         1         2  ...       766       767  is_sarcastic
0  0.180391  0.154627  0.102255  ... -0.009748  0.034562  0           
1  0.055346  0.057804 -0.007890  ...  0.004927  0.069538  1           
2  0.195907 -0.215209  0.234511  ... -0.019556  0.218400  0           
3  0.098043  0.133683 -0.001626  ...  0.003961  0.228541  1           
4  0.240887  0.041067  0.034774  ...  0.027298  0.097727  1           

[5 rows x 769 columns]

time: 122 ms (started: 2021-07-24 05:19:16 +00:00)


In [ ]:
test_gpt_2_df = pd.read_csv("datasets/test_gpt_2.csv") 
test_gpt_2_df.shape 

(4007, 769)

time: 2.65 s (started: 2021-07-24 05:19:16 +00:00)


In [ ]:
train_y = train_gpt_2_df.pop('is_sarcastic')
test_y = test_gpt_2_df.pop('is_sarcastic')

train_x = train_gpt_2_df
test_x = test_gpt_2_df

train_x.shape,train_y.shape,test_x.shape,test_y.shape

((22702, 768), (22702,), (4007, 768), (4007,))

time: 10.4 ms (started: 2021-07-24 05:19:18 +00:00)


## SVC

In [ ]:
from sklearn.svm import SVC
svc = SVC(kernel ='rbf', gamma = 0.1, C = 10, probability=True) #2h 56min
svc.fit(train_x,train_y)
pred=svc.predict(test_x)

time: 4h 30min 54s (started: 2021-07-24 05:20:38 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1739  509]
 [1340  419]]
Accuracy Score for LR with C=1.0  =0.5385575243324182
time: 16.4 ms (started: 2021-07-24 09:51:33 +00:00)


## Logistic Regression

In [ ]:
# Applying Logistic Regression 
model=LogisticRegression(max_iter=10000)
model.fit(train_x,train_y)
pred=model.predict(test_x)
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[2029  219]
 [1573  186]]
Accuracy Score for LR with C=1.0  =0.5527826303968056
time: 33.2 s (started: 2021-07-23 20:15:26 +00:00)


## KNN

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 25, weights = 'distance')
knn.fit(train_x,train_y)
pred=knn.predict(test_x)

time: 1min 10s (started: 2021-07-23 20:16:18 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1684  564]
 [1277  482]]
Accuracy Score for LR with C=1.0  =0.5405540304467182
time: 10.4 ms (started: 2021-07-23 20:17:28 +00:00)


## Decision Tree

In [ ]:
dt = DecisionTreeClassifier(criterion ='entropy', max_depth= None, min_samples_leaf=1, min_samples_split=20,splitter="best")
dt.fit(train_x,train_y)
pred=dt.predict(test_x)

time: 1min 8s (started: 2021-07-23 20:17:28 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1346  902]
 [1082  677]]
Accuracy Score for LR with C=1.0  =0.5048664836536062
time: 9.42 ms (started: 2021-07-23 20:18:37 +00:00)


## Random Forest

In [ ]:
rf = RandomForestClassifier(criterion='entropy',n_estimators = 100, max_depth = None, bootstrap = False)
rf.fit(train_x,train_y)
pred=rf.predict(test_x)

time: 4min 29s (started: 2021-07-23 20:18:37 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[1909  339]
 [1484  275]]
Accuracy Score for LR with C=1.0  =0.5450461692038931
time: 10.5 ms (started: 2021-07-23 20:23:07 +00:00)


## Naive Bayes

In [ ]:
gnb = GaussianNB()
gnb.fit(train_x,train_y)
pred=gnb.predict(test_x)

time: 330 ms (started: 2021-07-23 20:23:07 +00:00)


In [ ]:
print("Evaluate confusion matrix for LR")
print(confusion_matrix(test_y,pred))
print(f"Accuracy Score for LR with C=1.0  ={accuracy_score(test_y,pred)}")

Evaluate confusion matrix for LR
[[ 965 1283]
 [ 723 1036]]
Accuracy Score for LR with C=1.0  =0.4993760918392813
time: 10.4 ms (started: 2021-07-23 20:23:07 +00:00)
